config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :saveitems, only: %i[index show create destroy]
  resources :products, only: %i[index]

  delete '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create', as: :login
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :saveitem
  belongs_to :user
  validates :price, presence: true
  validates :user_id, presence: true
  validates :saveitem_id, presence: true

  def self.save_price(user, item, price)
    user.prices.create(
      saveitem: item,
      price: price
    )
  end

  def self.set_datas(user, item)
    prices = self.where(user: user, saveitem: item)
    datas = []
    prices.each do |price|
      data = ["#{price.created_at.strftime('%Y/%m/%d')}", price.price]
      datas.push(data)
    end
    return datas
  end

  def self.get_price(item, user)
    return self.order(updated_at: :desc).find_by(user: user, saveitem: item).price
  end
end

app/models/saveitem.rb
class Saveitem < ApplicationRecord
  belongs_to :user
  has_many :prices, dependent: :delete_all
  validates :item_code, presence: true, uniqueness: true
  validates :image_url, presence: true
  validates :url, presence: true
  validates :name, presence: true
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :uid, presence: true, uniqueness: true
  has_many :saveitems, dependent: :delete_all
  has_many :prices, dependent: :delete_all

  def self.find_or_create_account(auth)
    uid = auth[:uid]
    name = auth[:info][:name]

    User.find_or_create_by(uid: uid, name: name) do |user|
      user.name = name
      user.uid = uid
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user
  before_action :authenticate

  private

  def logged_in?
    !!current_user
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: "ログインしてください。"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate
  def index
    if params[:keyword]
      @keyword = params[:keyword]
      return if @items = RakutenWebService::Ichiba::Item.search(keyword: @keyword)
    end
  end
end

app/controllers/saveitems_controller.rb
class SaveitemsController < ApplicationController
  def index
    @items = Saveitem.where(user_id: current_user.id)
  end

  def show
    @saveitem = Saveitem.find(params[:id])
    @datas = Price.set_datas(current_user, @saveitem)
  end

  def create
    @saveitem = current_user.saveitems.build(saveitem_params)
    if @saveitem.save
      Price.save_price(current_user, @saveitem, params[:price])
      redirect_to saveitems_path, notice: "商品情報を保存しました。"
    else
      redirect_to products_path, alert: "商品の保存に失敗しました。"
    end
  end

  def destroy
    @saveitem = current_user.saveitems.find(params[:id])
    @saveitem.destroy
    redirect_to saveitems_path, notice: "商品情報を削除しました。"
  end

  private

  def saveitem_params
    params.permit(:item_code, :image_url, :url, :name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: :create
  def create
    user = User.find_or_create_account(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to saveitems_path, notice: "ログインしました。"
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました。"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_msg
    if flash[:notice]
      content_tag(:div, class: "alert alert-success") do
        flash[:notice]
      end
    end
  end

  def alert_msg
    if flash[:alert]
      content_tag(:div, class: "alert alert-danger") do
        flash[:alert]
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/saveitems_helper.rb
module SaveitemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RakutenPriceCheckerV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= image_tag("/image/logo.png", class: "navbar-brand") %>
          <% if logged_in? %>
            <ul class="navbar-nav">
              <li class="nav-item mr-2">
                <span class="navbar-text font-weight-bold">ログインユーザー：<%= current_user.name %></span>
              </li>
              <li class="nav-item navbar-text mx-3">|</li>
              <li class="nav-item">
                <%= link_to "商品検索", products_path, class: "nav-link" %>
              </li>
              <li class="nav-item navbar-text mx-3">|</li>
              <li class="nav-item">
                <%= link_to "保存商品一覧", saveitems_path, class: "nav-link" %>
              </li>
              <li class="nav-item navbar-text mx-3">|</li>
              <li class="nav-item mr-3">
                <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "Googleアカウントでログイン", "/auth/google_oauth2", method: :post, class: "nav-link mr-3" %>
              </li>
            </ul>
          <% end %>
        </div>
      </nav>
    </header>
    <%= flash_msg %>
    <%= alert_msg %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <%= form_with(url: products_path, method: :get, class: "text-center my-5") do |f| %>
    <%= f.label :keyword, "検索商品：" %>
    <%= f.text_field :keyword, value: "#{@keyword}", placeholder: "キーワード" %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>

  <table class="table table-warning rounded">
    <thead>
      <tr class="align-middle">
        <% if logged_in? %>
          <th class="col-1"></th>
        <% end %>
        <th class="col-1 align-middle">イメージ</th>
        <th class="align-middle">商品名</th>
        <th class="align-middle col-2 text-center">値段(円)</th>
      </tr>
    </thead>
    <% if @items %>
      <% @items.each do |item| %>
        <tbody>
          <tr>
            <% if logged_in? %>
              <td class="align-middle text-center">
                <%= link_to "保存", saveitems_path(item_code: item['itemCode'], image_url: item['smallImageUrls'][0], url: item['itemUrl'], name: item['itemName'], price: item['itemPrice']), method: :post, class: "btn btn-primary btn-sm" %>
              </td>
            <% end %>
            <td class="text-center"><img src="<%= item['smallImageUrls'][0] %>"></td>
            <td><a href="<%= item['itemUrl'] %>" target="_blank"><%= item['itemName'] %></a></td>
            <td class="align-middle text-center"><%= item['itemPrice'] %></td>
          </tr>
        </tbody>
      <% end %>
    <% end %>
  </table>
</div>

app/views/saveitems/index.html.erb
<div class="container">
  <h3 class="my-5 font-weight-bold text-center">保存商品一覧</h3>
  <table class="table table-warning rounded">
    <thead>
      <tr>
        <th class="col-2 text-center align-middle">価格チェック</th>
        <th class="col-1 align-middle">イメージ</th>
        <th class="align-middle">商品名</th>
        <th class="align-middle col-2 text-center">値段(円)</th>
      </tr>
    </thead>
    <% if @items %>
      <% @items.each do |item| %>
        <tbody>
          <tr>
            <td class="align-middle text-center">
              <%= link_to "価格チェック", saveitem_path(item), class: "btn btn-primary btn-sm" %>
            </td>
            <td class="text-center"><img src="<%= item.image_url %>"></td>
            <td><a href="<%= item.url %>" target="_blank"><%= item.name %></a></td>
            <td class="align-middle text-center"><%= Price.get_price(item, current_user) %></td>
          </tr>
        </tbody>
      <% end %>
    <% end %>
  </table>
</div>

app/views/saveitems/show.html.erb
<div class="container">
  <div class="my-5 d-flex align-items-center">
    <img src="<%= @saveitem.image_url %>" class="mr-3">
    <a href="<%= @saveitem.url %>" target="_blank"><%= @saveitem.name %></a>
    <%= link_to "削除", saveitem_path(@saveitem), method: :delete, class: "btn btn-danger btn-sm ml-3" %>
  </div>
  <%= line_chart @datas, width: "100%", height: "500px" %>
</div>